services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage     

volumes:
  qdrant-data:      